export const AUTHORIZE = "AUTHORIZE";
export const DEAUTHORIZE = "DEAUTHORIZE";
export const TOGGLE_REGISTER_MODAL = "TOGGLE_REGISTER_MODAL";
export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL";

export const LOAD_POSTS = "LOAD_POSTS";
export const SET_SINGLE_POST = "SET_SINGLE_POST";
export const TOGGLE_EDIT_POST = "TOGGLE_EDIT_POST";
export const EDIT_POST_INPUT = "EDIT_POST_INPUT";

export const ADD_COMMENT = "ADD_COMMENT";
export const TOGGLE_REPLY_FORM = "TOGGLE_REPLY_FORM";
export const COMMENT_REPLY = "COMMENT_REPLY";
export const REPLY_INPUT = "REPLY_INPUT";
export const RESET_REPLY_INPUT = "RESET_REPLY_INPUT";
export const SET_DELETED_COMMENT = "SET_DELETED_COMMENT";
export const TOGGLE_EDIT_COMMENT = "TOGGLE_EDIT_COMMENT";
export const EDIT_COMMENT_INPUT = "EDIT_COMMENT_INPUT";
export const TOGGLE_SHOW_COMMENT = "TOGGLE_SHOW_COMMENT";
export const SET_SINGLE_POST_COMMENTS = "SET_SINGLE_POST_COMMENTS";

export const SET_TOPICS = "SET_TOPICS";
export const SET_ADDED_TOPIC = "SET_ADDED_TOPIC";

export const SET_SIDEBAR = "SET_SIDEBAR";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const SET_ERROR = "SET_ERROR";
export const SET_SUCCESS = "SET_SUCCESS";
export const SET_LOADING = "SET_LOADING";
export const SET_TIMEOUT = "SET_TIMEOUT";